### ISSUE TITLE
MS Edge compatibility ?

### ISSUE THREAD

**Issue by heyadityak** [dhruvp-8/file-transfer#1]
This app is not compatible with MS Edge. What shall be done for support for Edge ?

**Comment by heyadityak** [comment]
Are there any polyfills available for the same ? try using that :)

**Comment by dhruvp-8** [comment]
This WEBRTC Technology is only for Chrome & FireFox and it's still in process of building so i dont think ployfills would help the cause!

**Comment by heyadityak** [comment]
Please check this link : 

https://blogs.windows.com/msedgedev/2017/01/31/introducing-webrtc-microsoft-edge/
